In [17]:
import pandas as pd

In [18]:
import numpy as np

In [ ]:
from sklearn.metrics import accuracy_score

In [19]:
df = pd.read_csv('/Users/mayurarvind/Downloads/sent/train.csv')

/usr/local/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3049: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [20]:
df['label'].unique()

array([1, 2, 0, '1', '2', '0',
       'My husband and I had not purchased a home before and we definitely needed some hand holding. They were patient and professional. We got our dream home and the entire experience was awesome! Thank you so much ladies for a job well done!'],
      dtype=object)

In [21]:
#erroneous label
df = df[df['label'] != 'My husband and I had not purchased a home before and we definitely needed some hand holding. They were patient and professional. We got our dream home and the entire experience was awesome! Thank you so much ladies for a job well done!']

In [22]:
df['label'] = pd.to_numeric(df.label)

In [23]:
df['label'].unique()

array([1, 2, 0])

In [24]:
df.head()

label                                               text
0      1  Great mobile app with nice reward program. Mak...
1      2  Really fast and polite. Definitely recommend. ...
2      2  This place is always amazing, friendly staff a...
3      1  We did a Wine 101 class on a Friday night. Coo...
4      1  I am rounding up because I think this place ma...

In [25]:
X = df['text'].values
y = df['label'].values

In [27]:
i = np.random.permutation(len(X))

In [28]:
X_train = X[i[:350000]]
y_train = y[i[:350000]]

X_test = X[i[350000:]]
y_test = y[i[350000:]]

In [29]:
from sklearn.feature_extraction.text import CountVectorizer
vect = CountVectorizer()
X_train_dtm = vect.fit_transform(X_train)
X_test_dtm = vect.transform(X_test)

In [32]:
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB()
nb.fit(X_train_dtm, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [34]:
accuracy_score(nb.predict(X_train_dtm), y_train)

0.8264657142857142

In [35]:
accuracy_score(nb.predict(X_test_dtm), y_test)

0.81548

In [36]:
from sklearn.neural_network import MLPClassifier
mlp = MLPClassifier(early_stopping=True)
mlp.fit(X_train_dtm, y_train)

In [20]:
from sklearn.metrics import accuracy_score

In [43]:
accuracy_score(mlp.predict(X_train_dtm), y_train)

0.9283085714285715

In [76]:
accuracy_score(mlp.predict(X_test_dtm), y_test)

0.90048

In [140]:
#example of positive sample
ex_pos = np.array(["I thoroughly enjoyed the food at the restaurant and would highly recommend it to everyone."])

In [141]:
#example of negative sample
ex_neg = np.array(["The trains were very dirty and I will never travel by them again"])

In [142]:
#predictions
ex_dtm = vect.transform(ex_pos)
mlp.predict(ex_dtm)

array([2])

In [143]:
ex_dtm = vect.transform(ex_neg)
mlp.predict(ex_dtm)

array([0])